# Sidebar navigation

- label: 'Introdução'
  link: '/'
- label: JavaScript (Vanilla)
  items:
    - label: '1. Variáveis e tipos de dados'
      link: '/js/var'
    - label: '2. Operadores'
      link: '/js/operators'
- label: Comunidade
  items:
    - label: 'Github'
      link: 'https://github.com/renangabriel27/js-guide'